name: List AWS Services (Botocore)

on:

  workflow_dispatch:  

jobs:
  list-services:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Use latest stable version

      - name: Install boto3 and botocore
        run: |
          pip install --upgrade boto3 botocore

      - name: Run script to list services
        run: |
          python3 .github/workflows/services.py


      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated commit by GitHub Actions"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          
